version: '3'

services:
  proxy_server:
    build: .
    depends_on:
      - 'item_detail'
      - 'related_product'
    ports:
      - '8000:8000'

  item_detail:
    image: hanyuzhu/item_detail:latest
    depends_on:
      - 'database'
    ports:
      - '8004:8004'

  related_product:
    image: ivyzheng/related-product:latest
    depends_on:
      - 'database'
    ports:
      - '8001:8001'

  database:
    image: mongo:latest
